ecommerce_growth:
    target: dev
    outputs:
        dev:
            type: snowflake
            account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
            user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
            private_key_path: "{{ env_var('PRIVATE_KEY_PATH') }}"
            role: ACCOUNTADMIN
            database: ANALYTICS_DEV
            warehouse: DBT_WH
            schema: DEV
            threads: 4
    
    
        ci:
            type: snowflake
            account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
            user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
            private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
            role: ACCOUNTADMIN
            database: ANALYTICS_CI
            warehouse: DBT_WH
            schema: "{{ env_var('DBT_SCHEMA') }}"

        prod:
            type: snowflake
            account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
            user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
            private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
            role: ACCOUNTADMIN
            database: ANALYTICS_PROD
            warehouse: DBT_WH
            schema: PROD

