
name: dbt CD - Deploy to Prod

on:
  push:
    branches:
      - main        # ← triggers when PR merges to main
  workflow_dispatch:

jobs:
  dbt-prod-run:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}
      DBT_DATABRICKS_HOST: ${{ secrets.DBT_DATABRICKS_HOST }}
      DBT_DATABRICKS_HTTP_PATH: ${{ secrets.DBT_DATABRICKS_HTTP_PATH }}
      # Databricks CLI credentials
      DATABRICKS_HOST: ${{ secrets.DBT_DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DBT_DATABRICKS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        uses: databricks/setup-cli@v0.221.0

      - name: Build Docker Image
        run: docker build -t dbt-local .
      
      - name: Run dbt Production Build in Docker
        run: |
          docker run --rm \
            -v ${PWD}/target:/usr/app/target \
            -e DBT_DATABRICKS_HOST="${{ secrets.DBT_DATABRICKS_HOST }}" \
            -e DBT_DATABRICKS_HTTP_PATH="${{ secrets.DBT_DATABRICKS_HTTP_PATH }}" \
            -e TOKEN="${{ secrets.DBT_DATABRICKS_TOKEN }}" \
            dbt-local sh -c "dbt deps && dbt build --target prod"

      - name: Upload updated manifest.json to Databricks Volume
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks fs cp ./target/manifest.json dbfs:/Volumes/analytics/default/dbt_state/manifest.json --overwrite
      
