name: dbt Slim CI

on:
  pull_request:
    branches:
      - main

jobs:
  slim_ci_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Fetch Main Branch
        run: git fetch origin main:main

      
      - name: Install Databricks CLI
        uses: databricks/setup-cli@v0.221.0

      - name: Fetch Prod Manifest from Databricks Volume
        env:
          # Dynamically prepends https:// for databricks-cli while leaving the GitHub Secret clean for dbt
          DATABRICKS_HOST: "https://${{ secrets.DBT_DATABRICKS_HOST }}"
          DATABRICKS_TOKEN: ${{ secrets.DBT_DATABRICKS_TOKEN }}
        run: |
          mkdir -p ./state
          databricks fs cp dbfs:/Volumes/analytics/default/dbt_state/manifest.json \
            ./state/manifest.json || echo "No production manifest found."
      
      - name: Build Docker Image
        run: docker build -t dbt-local .

      # To run Slim CI, dbt needs the production state. x
      - name: Run dbt Slim CI in Docker
        run: |
          docker run --rm \
            -v ${PWD}/state:/app/state \
            -e DBT_DATABRICKS_HOST="${{ secrets.DBT_DATABRICKS_HOST }}" \
            -e TOKEN="${{ secrets.DBT_DATABRICKS_TOKEN }}" \
            -e DBT_DATABRICKS_HTTP_PATH="${{ secrets.DBT_DATABRICKS_HTTP_PATH }}" \
            -e DBT_SCHEMA="pr_${{ github.event.number }}" \
            dbt-local sh -c "dbt deps && dbt build --select state:modified+ --defer --state state --target dev_scratch"
