name: CI Schema Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  drop_ci_schema:
    runs-on: ubuntu-latest
    steps:
      - name: Install Databricks CLI
        uses: databricks/setup-cli@v0.221.0

      - name: Drop Temporary PR Schema
        env:
          DATABRICKS_HOST: "https://${{ secrets.DBT_DATABRICKS_HOST }}"
          DATABRICKS_TOKEN: ${{ secrets.DBT_DATABRICKS_TOKEN }}
        run: |
          databricks sql run \
            --warehouse-id ${{ secrets.DATABRICKS_SQL_WAREHOUSE_ID }} \
            --query "DROP SCHEMA IF EXISTS analytics.pr_${{ github.event.pull_request.number }} CASCADE;"