name: CI Schema Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  drop_ci_schema:
    runs-on: ubuntu-latest
    steps:
      - name: Install Databricks CLI
        uses: databricks/setup-cli@v0.221.0

      - name: Drop Temporary PR Schema
        env:
          DATABRICKS_HOST: "https://${{ secrets.DBT_DATABRICKS_HOST }}"
          DATABRICKS_TOKEN: ${{ secrets.DBT_DATABRICKS_TOKEN }}
        run: |
                curl -s -X POST "${DATABRICKS_HOST}/api/2.0/sql/statements" \
                  -H "Authorization: Bearer ${DATABRICKS_TOKEN}" \
                  -H "Content-Type: application/json" \
                  -d "{
                    \"warehouse_id\": \"${WAREHOUSE_ID}\",
                    \"statement\": \"DROP SCHEMA IF EXISTS analytics.pr_${PR_NUMBER} CASCADE;\"
                  }"